#!/bin/bash

# Default values
DEFAULT_OUTPUT="output.txt"
TO_BE_IGNORED_BY_DEFAULT=".*\.git/.*"

usage() {
    local script="$(basename $0)"

    echo -e "${script} - Fuse all contents of the current branch into only one file.\n" \
        "${script} [OPTIONS] [ARGUMENTS]\n" \
        "\n" \
        "OPTIONS\n" \
        "-h, --help\n" \
        "\tDisplay help.\n" \
        "-n, --no-ignore\n" \
        "\tDo not ignore files or folders ignored by Git.\n" \
        "\tBy default, all files or folders ignored by Git are ignored.\n" \
        "\tOptional.\n" \
        "-o, --output OUTPUT_FILE_PATH\n" \
        "\tStore all contents in the output file with the OUT_FILE_PATH path.\n" \
        "\tBy default, the output file path is '${DEFAULT_OUTPUT}'.\n" \
        "\tOptional."
}

store() {
    [ -z "${output}" ] && exit 1 || cat | tee --append "${output}"
}

printFileNameAsHeader() {
    # FUNC ARGS
    local fileName="$1"
    # END  ARGS

    echo -e \
        " =================================================================\n" \
        "File: ${fileName}\n" \
        "_________________________________________________________________"
}

whatToIgnore() {
    if [ "${noIgnore}" == "true" ] || [ ! -f ".gitignore" ]; then
        local readyForFind="${TO_BE_IGNORED_BY_DEFAULT}"
    elif [ -f ".gitignore" ]; then
        local ignoredByGit=$(sed -r '/^(#.*)?$/d' .gitignore | paste -sd '|')
        local readyForFind=$(echo "${ignoredByGit}" | sed 's/\./\\./g; s/\*/.*/g; s/|/\\|/g')"\|${TO_BE_IGNORED_BY_DEFAULT}"
    fi
    echo "${readyForFind}"
}

listTargetFiles() {
    # FUNC ARGS
    local files=("${@:1:$#-1}") output="${@:(-1)}"
    # END  ARGS

    echo "Target files for fusion:" | store
    {
        for file in "${files[@]}"; do
            printf "%s %s %s\n" "${file}" $(wc -l "${file}" | awk '{ print $1 }') "lines"
        done;
    } | column -t | store
    echo | store
}

gitFuse() {
    local output="${outputFilePath:=${DEFAULT_OUTPUT}}"

    rm -f "${output}"

    local toFuse=($(find . -type f ! -regex "$(whatToIgnore)"))
    listTargetFiles "${toFuse[@]}" "${output}"

    for file in "${toFuse[@]}"; do
        echo "$(printFileNameAsHeader ${file})" | store
        cat  "${file}" | store
    done
}

main() {
    # FUNC ARGS
    local args=("$@")
    # END  ARGS

    for arg in "${args[@]}"; do
        shift
        case "${arg}" in
        --help)
            set -- "$@" "-h"
            ;;
        --no-ignore)
            set -- "$@" "-n"
            ;;
        --output)
            set -- "$@" "-o"
            ;;
        *)
            set -- "$@" "${arg}"
            ;;
        esac
    done

    local outputFilePath="" noIgnore=false

    while getopts "hno:" option; do
        case "${option}" in
        h)
            usage && exit 0
            ;;
        n)
            noIgnore=true
            ;;
        o)
            outputFilePath="${OPTARG}"
            ;;
        esac
    done

    gitFuse
}

main $*
